version: '3.8'

services:
  mongodb:
    image: mongo
    environment:
      # MONGO_INITDB_ROOT_USERNAME: admin
      # MONGO_INITDB_ROOT_PASSWORD: 123mudar
      - PUID=1000
      - PGID=1000
    volumes: 
      - ./data/mongo:/data/db
    ports: 
      - 27017:27017